# welcome to numpy tutorial

In [1]:
import numpy as np

In [8]:
# l1 = [1,2,3,44,5,6]

n1 = np.array([[1,2,3,44,5,6]], np.int8)          #int8, 32, 64 as per memory allocation

In [9]:
n1[0,2] = 45

In [10]:
n1

array([[ 1,  2, 45, 44,  5,  6]], dtype=int8)

In [236]:
n1.min()

1

In [237]:
n1.max()

45

In [238]:
n1.sum()

103

In [4]:
n1

array([[ 1,  2, 45, 44,  5,  6]], dtype=int8)

In [5]:
n1.shape

(1, 6)

In [6]:
n1.dtype

dtype('int8')

In [13]:
n2 = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])

print(n2)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [8]:
zeros = np.zeros((2,5))

In [9]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
zeros.dtype

dtype('float64')

In [11]:
 arg = np.arange(20,100,5)

In [24]:
arg

array([20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95])

In [25]:
np.NINF

-inf

In [28]:
lspace = np.linspace(1,4,8)

In [29]:
lspace

array([1.        , 1.42857143, 1.85714286, 2.28571429, 2.71428571,
       3.14285714, 3.57142857, 4.        ])

In [56]:
emp = np.empty((2,6))

In [61]:
emp

array([[1.10447826e-311, 3.16202013e-322, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 9.96357572e-043],
       [3.37995830e-057, 2.25161530e+184, 4.31569518e-061,
        2.78859930e+179, 2.19217284e-076, 1.68812777e+160]])

In [75]:
emp_like = np.empty_like(lspace)

In [76]:
emp_like

array([1.        , 1.42857143, 1.85714286, 2.28571429, 2.71428571,
       3.14285714, 3.57142857, 4.        ])

In [83]:
ide = np.identity(4)

In [84]:
ide

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [102]:
arr = np.arange(100)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [111]:
arre = arr.reshape(10,10)   #can enter 10,10.  5,20. 4,25

In [112]:
arre

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [116]:
rvl = arr.ravel()   #convert into previous shape 

In [117]:
rvl

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [118]:
 x = [[1,4,7],[2,5,8],[3,6,9]]

In [120]:
ar = np.array(x)

In [131]:
ar

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [122]:
ax = ar.sum(axis = 0)       #axis 0 = row side axis

In [123]:
ax

array([ 6, 15, 24])

In [124]:
ax1 = ar.sum(axis = 1)       #axis 1 = colum side axis

In [125]:
ax1

array([12, 15, 18])

In [128]:
art = ar.T         #'transpose' ,convert row to colum

art

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [134]:
art.flat    # for itration use

In [135]:
for i in art.flat:
    print(i)

1
2
3
4
5
6
7
8
9


In [136]:
art.ndim   #insert number of dimantions

2

In [137]:
art.shape

(3, 3)

In [138]:
art.size

9

In [140]:
art.nbytes  # number of bytes use

36

In [163]:
one = np.array([2,3,5,10,1,45,82,10,2,6,8])

In [164]:
one.argmax()   #find no.of index which is maximum value

6

In [165]:
one.argmin()

4

In [166]:
one.argsort()    # in assanding order find values

array([ 4,  0,  8,  1,  2,  9, 10,  3,  7,  5,  6], dtype=int64)

In [167]:
one.dtype

dtype('int32')

In [196]:
mat = np.array([[5,9,1],[4,2,9],[8,9,6],[9,6,7]])

mat

array([[5, 9, 1],
       [4, 2, 9],
       [8, 9, 6],
       [9, 6, 7]])

In [197]:
mat.argmax()   #first change in one array and find index which is given argumant

1

In [198]:
mat.argmin()

2

In [199]:
mat.argsort()

array([[2, 0, 1],
       [1, 0, 2],
       [2, 0, 1],
       [1, 2, 0]], dtype=int64)

In [200]:
mat.argmax(axis = 0)

array([3, 0, 1], dtype=int64)

In [201]:
mat.argmax(axis = 1)

array([1, 2, 1, 0], dtype=int64)

In [203]:
mat.argsort(axis = 0)

array([[1, 1, 0],
       [0, 3, 2],
       [2, 0, 3],
       [3, 2, 1]], dtype=int64)

In [202]:
mat

array([[5, 9, 1],
       [4, 2, 9],
       [8, 9, 6],
       [9, 6, 7]])

In [207]:
mat.ravel()

array([5, 9, 1, 4, 2, 9, 8, 9, 6, 9, 6, 7])

In [215]:
print(mat.shape)
print(mat.size)
print(mat.dtype)

(4, 3)
12
int32


In [210]:
mat.reshape(2,6)

array([[5, 9, 1, 4, 2, 9],
       [8, 9, 6, 9, 6, 7]])

In [218]:
mat2 = np.array([[5,0,1],[6,4,2],[1,2,3]])

In [219]:
zat = np.array([[5,2,1],[4,2,1],[3,4,6]])

In [221]:
mat2+zat

array([[10,  2,  2],
       [10,  6,  3],
       [ 4,  6,  9]])

In [222]:
mat2*zat

array([[25,  0,  1],
       [24,  8,  2],
       [ 3,  8, 18]])

In [223]:
mat2-zat

array([[ 0, -2,  0],
       [ 2,  2,  1],
       [-2, -2, -3]])

In [229]:
mat2/zat

array([[1.        , 0.        , 1.        ],
       [1.5       , 2.        , 2.        ],
       [0.33333333, 0.5       , 0.5       ]])

In [232]:
blk = np.array([2,4,6,9])


np.sqrt(blk)  #find square root

array([1.41421356, 2.        , 2.44948974, 3.        ])

In [240]:
mat

array([[5, 9, 1],
       [4, 2, 9],
       [8, 9, 6],
       [9, 6, 7]])

In [244]:
np.where(mat>8)    #find given argument in tuple form

(array([0, 1, 2, 3], dtype=int64), array([1, 2, 1, 0], dtype=int64))

In [245]:
type(np.where(mat>7))

tuple

In [262]:
zer = np.array([[2,3,0],[6,9,2],[5,0,2]])

zer

array([[2, 3, 0],
       [6, 9, 2],
       [5, 0, 2]])

In [259]:
np.count_nonzero(zer)

7

In [260]:
np.nonzero(zer)

(array([0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 0, 1, 2, 0, 2], dtype=int64))

In [264]:
zer[1,1] = 0

zer

array([[2, 3, 0],
       [6, 0, 2],
       [5, 0, 2]])

In [265]:
np.nonzero(zer)

(array([0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 0, 2, 0, 2], dtype=int64))